name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: {python-version: '3.9'}
      - run: |
          pip install buildozer cython
          sudo apt update
          sudo apt install -y openjdk-17-jdk zip
          buildozer android debug
      - uses: actions/upload-artifact@v2
        with:
          name: MINE-APK
          path: bin/*.apk
