name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
      - uses: actions/checkout@v4
      - run: buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: MINE-APK
          path: bin/*.apk
